#! /bin/bash
#
# mvb -- mv back
#
# Usage:
#   mvb [<options>] <path1> <path2>
#

__mvb() {
    local opts=

    while true; do
        case "$1" in
            -*)
                opts="$opts $1";
                shift ;;
            *)
                break
        esac
    done

    mv $opts $2 $1
}

__mvb $*
